name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  destroy_infra:
    name: Destroy infrastructure
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials (STS)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Terraform Init (infra)
        working-directory: terraform
        run: terraform init

      - name: Terraform Destroy (infra)
        working-directory: terraform
        run: terraform destroy -auto-approve

  destroy_bootstrap:
    name: Destroy S3 backend
    runs-on: ubuntu-latest
    needs: destroy_infra   # ⬅️ ordre inverse

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials (STS)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Terraform Init (bootstrap)
        working-directory: bootstrap
        run: terraform init

      - name: Terraform Destroy (bootstrap)
        working-directory: bootstrap
        run: terraform destroy -auto-approve
