name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - "bootstrap/**"
      - "terraform/**"

jobs:
  bootstrap:
    name: Bootstrap S3 backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials (STS)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Terraform Init (bootstrap)
        working-directory: bootstrap
        run: terraform init

      - name: Terraform Apply (bootstrap)
        working-directory: bootstrap
        run: terraform apply -auto-approve

  terraform:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    needs: bootstrap   # ⬅️ dépend du job S3

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials (STS)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Terraform Init (infra)
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply (infra)
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Terraform Outputs
        working-directory: terraform
        run: terraform output
